version: '3'
services:
  flask-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-backend
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - flask-backend

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
