# Streamlit Frontend Dockerfile
FROM python:3.9-slim

WORKDIR /frontend

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy frontend code
COPY . .

# Expose Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "front.py", "--server.port=8501"]